name: ${project.name}
description: ${project.description}
website: ${project.url}
version: ${plugin.version}
main: fr.maesia.mob.maesiamob.MaesiaMob
api-version: 1.18
authors: [ novah95 ]
commands:
  moremob:
    description: Creation of new monsters.
    aliases: mm
  bestiaire:
    description: List of creatures.
    aliases: b