name: MaesiaMob
version: '${project.version}'
main: fr.maesia.mob.MaesiaMob
api-version: 1.19
authors: [ novah95 ]
softdepend:
  - Skills
commands:
  MaesiaMob:
    description: Création de nouveau mobs.
    aliases: mm
  Bestiaire:
    description: List des créatures.
    aliases: b
  Spawner:
    description: Gestion des spawner
    aliases: sp
